
services:
  train-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public:ro  # Mount public folder for live updates
      - ./data:/app/data  # Persist database and other data
    environment:
      - NODE_ENV=development
      - LDBWS_API_KEY=${LDBWS_API_KEY:-your-api-key-here}
      - LDBWS_BASE_URL=${LDBWS_BASE_URL:-https://api1.raildata.org.uk/1010-live-departure-board-dep1_2}
      - PORT=3000
    restart: unless-stopped