# fly.toml app configuration file generated for play-vtm7ea on 2025-09-21T14:46:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'play-vtm7ea'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
LDBWS_BASE_URL = "https://api1.raildata.org.uk/1010-live-departure-board-dep1_2"
NEXTDEPS_BASE_URL = "https://api1.raildata.org.uk/1010-live-departure-board-dep1_2"
NODE_ENV = "production"
PORT = "3000"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
