# Fly.io configuration for Next Train app
app = "next-train-pad-tlh"
primary_region = "lhr"

[build]

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3000
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
grace_period = "5s"
interval = "10s"
method = "get"
path = "/api/health"
protocol = "http"
timeout = "2s"

[[mounts]]
destination = "/app/data"
source = "data"

[env]
LDBWS_BASE_URL = "https://api1.raildata.org.uk/1010-live-departure-board-dep1_2"
NEXTDEPS_BASE_URL = "https://api1.raildata.org.uk/1010-live-departure-board-dep1_2"
NODE_ENV = "production"
PORT = "3000"
